from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    FarmerRegistrationView,
    AnnouncementViewSet,
    MessageViewSet,
    inbox,
    broadcast,
    mark_message_read,
    farmer_dashboard,
    agent_dashboard,
    partner_dashboard,
    partner_external_analysis,
    partner_external_dataset_intelligence,
    partner_field_agent_data_center,
    partner_standalone_analysis,
    dataset_analysis_mode_selector,
    create_farmer,
    admin_dashboard,
    create_user,
    contact_submissions_admin,
    assign_farmer_request,
    review_farmer,
    approve_farmer,
    reject_farmer,
    request_more_info,
    mark_notification_read,
    generate_password_reset_link,
    upload_admin_profile_photo,
    upload_agent_profile_photo,
    upload_investor_profile_photo,
    request_password_reset_from_admin,
    force_password_change,
    farm_assessment_sheet1,
    farm_assessment_sheet2,
    farm_assessment_sheet3,
    partner_dataset_upload,
    confirm_dataset_domain_classification,
    dataset_analysis_state,
    data_prep_workspace,
    data_prep_column_operation,
    data_prep_row_operation,
    data_prep_undo_redo,
    data_prep_preview,
    dataset_audit_log_viewer,
    partner_powerbi_embedded,
    partner_powerbi_embed_config,
    partner_powerbi_refresh_dataset,
    partner_dataset_list,
    partner_dataset_join_suggest,
    partner_api_dataset_ingest,
    superuser_dashboard_selector,
    superuser_dashboard_gate,
)

router = DefaultRouter()
router.register(r'announcements', AnnouncementViewSet, basename='announcement')
router.register(r'messages', MessageViewSet, basename='message')

urlpatterns = [
    path('register/', FarmerRegistrationView.as_view(), name='farmer-register'),
    path('superuser/dashboard-selector/', superuser_dashboard_selector, name='superuser_dashboard_selector'),
    path('superuser/dashboard-gate/', superuser_dashboard_gate, name='superuser_dashboard_gate'),

    # Dashboards
    path('farmer/dashboard/', farmer_dashboard, name='farmer_dashboard'),
    path('agent/dashboard/', agent_dashboard, name='agent_dashboard'),
    path('partner/dashboard/', partner_dashboard, name='partner_dashboard'),
    path('partner/external-analysis/', partner_external_analysis, name='partner_external_analysis'),
    path('partner/external-dataset-intelligence/', partner_external_dataset_intelligence, name='partner_external_dataset_intelligence'),
    path('partner/field-agent-data-center/', partner_field_agent_data_center, name='partner_field_agent_data_center'),
    path('partner/standalone-analysis/', partner_standalone_analysis, name='partner_standalone_analysis'),
    path('partner/datasets/analysis-mode-selector/', dataset_analysis_mode_selector, name='dataset_analysis_mode_selector'),
    path('partner/powerbi/', partner_powerbi_embedded, name='partner_powerbi_embedded'),
    path('partner/powerbi/embed-config/', partner_powerbi_embed_config, name='partner_powerbi_embed_config'),
    path('partner/powerbi/refresh/', partner_powerbi_refresh_dataset, name='partner_powerbi_refresh_dataset'),
    path('governance/audit-logs/', dataset_audit_log_viewer, name='dataset_audit_log_viewer'),
    path('partner/datasets/upload/', partner_dataset_upload, name='partner_dataset_upload'),
    path('partner/datasets/api-ingest/', partner_api_dataset_ingest, name='partner_api_dataset_ingest'),
    path('partner/datasets/confirm-domain/', confirm_dataset_domain_classification, name='confirm_dataset_domain_classification'),
    path('partner/datasets/analysis-state/', dataset_analysis_state, name='dataset_analysis_state'),
    path('partner/datasets/list/', partner_dataset_list, name='partner_dataset_list'),
    path('partner/datasets/join-suggest/', partner_dataset_join_suggest, name='partner_dataset_join_suggest'),
    path('partner/datasets/data-prep/', data_prep_workspace, name='data_prep_workspace'),
    path('partner/datasets/data-prep/column-op/', data_prep_column_operation, name='data_prep_column_operation'),
    path('partner/datasets/data-prep/row-op/', data_prep_row_operation, name='data_prep_row_operation'),
    path('partner/datasets/data-prep/undo-redo/', data_prep_undo_redo, name='data_prep_undo_redo'),
    path('partner/datasets/data-prep/preview/', data_prep_preview, name='data_prep_preview'),
    path('partner/profile-photo/upload/', upload_investor_profile_photo, name='upload_investor_profile_photo'),
    path('admin/dashboard/', admin_dashboard, name='admin_dashboard'),
    path('force-password-change/', force_password_change, name='force_password_change'),

    # Field agent actions
    path('agent/create-farmer/', create_farmer, name='create_farmer'),
    path('agent/profile-photo/upload/', upload_agent_profile_photo, name='upload_agent_profile_photo'),

    # Admin actions
    path('admin/create-user/', create_user, name='create_user'),
    path('admin/contact-submissions/', contact_submissions_admin, name='contact_submissions_admin'),
    path('admin/assign-farmer/', assign_farmer_request, name='assign_farmer_request'),
    path('admin/review-farmer/<int:farmer_id>/', review_farmer, name='review_farmer'),
    path('admin/approve-farmer/<int:farmer_id>/', approve_farmer, name='approve_farmer'),
    path('admin/reject-farmer/<int:farmer_id>/', reject_farmer, name='reject_farmer'),
    path('admin/request-info/<int:farmer_id>/', request_more_info, name='request_more_info'),
    path('admin/notification/<int:notification_id>/read/', mark_notification_read, name='mark_notification_read'),
    path('admin/users/<int:user_id>/reset-link/', generate_password_reset_link, name='generate_password_reset_link'),
    path('admin/profile-photo/upload/', upload_admin_profile_photo, name='upload_admin_profile_photo'),

    # Farm Assessment (Three-Sheet Data Collection)
    path('agent/assessment/<int:farmer_id>/sheet1/', farm_assessment_sheet1, name='farm_assessment_sheet1'),
    path('agent/assessment/<int:farmer_id>/sheet2/', farm_assessment_sheet2, name='farm_assessment_sheet2'),
    path('agent/assessment/<int:farmer_id>/sheet3/', farm_assessment_sheet3, name='farm_assessment_sheet3'),

    # Messaging
    path('messages/inbox/', inbox, name='inbox'),
    path('messages/broadcast/', broadcast, name='broadcast'),
    path('messages/<int:message_id>/read/', mark_message_read, name='mark_message_read'),

    # API routes
    path('', include(router.urls)),
]
