# Generated by Django 5.2.7 on 2025-11-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=150)),
                ('farm_size', models.DecimalField(decimal_places=2, help_text='Farm size in hectares', max_digits=6)),
                ('cocoa_planted', models.PositiveIntegerField(help_text='Number of cocoa trees planted')),
                ('last_harvest_tons', models.DecimalField(decimal_places=2, help_text='Last harvest yield in tons', max_digits=6)),
                ('total_production_tons', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
