# Generated by Django 5.2.7 on 2025-11-03 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='cocoa_planted',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='last_harvest_tons',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='total_production_tons',
        ),
        migrations.AddField(
            model_name='farmer',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(default='0000000000', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('size_in_acres', models.FloatField()),
                ('cocoa_trees_planted', models.IntegerField()),
                ('date_established', models.DateField()),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='Farmers.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_harvest', models.DateField()),
                ('tons_produced', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quality_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='Farmers.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_date', models.DateField(auto_now_add=True)),
                ('purpose', models.CharField(max_length=200)),
                ('roi_percentage', models.FloatField(blank=True, help_text='Expected Return on Investment in %', null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='Farmers.farmer')),
            ],
        ),
    ]
