# Generated by Django 5.2.7 on 2025-12-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
