# Generated by Django 5.2.7 on 2025-12-24 02:27

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0006_rename_body_message_content_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='farmer_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='farmer_permissions_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('field_agent', 'Field Agent'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
    ]
