# Generated by Django 5.2.7 on 2026-01-02 02:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0008_alter_farm_farmer_alter_farmer_farmer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='cocoa_trees_planted',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='date_established',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='size_in_acres',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount_invested',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='investment_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='roi_percentage',
        ),
        migrations.AddField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farm',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='Farmers.farmer'),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_in_hectares',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='expected_return_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='Farmers.farm'),
        ),
        migrations.AddField(
            model_name='investment',
            name='invested_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investments_made', to='Farmers.farmer'),
        ),
    ]
