# Generated by Django 6.0.3 on 2026-03-31 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0010_farm_location_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
