# Generated by Django 6.0.3 on 2026-03-31 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0010_farm_location_userprofile_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmactivity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='crop_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='date_planted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='expected_yield_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='farm_size',
            field=models.FloatField(blank=True, help_text='Size in hectares', null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='harvest_date',
            field=models.DateField(blank=True, help_text='Approximate harvest date', null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='seeds_planted_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seeds planted in kg', max_digits=10, null=True),
        ),
    ]
