# Generated by Django 6.0.3 on 2026-04-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0010_farm_location_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FarmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_location', models.CharField(max_length=255)),
                ('farm_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('crop_type', models.CharField(max_length=100)),
                ('date_planted', models.DateField()),
                ('approx_harvest_date', models.DateField(blank=True, null=True)),
                ('expected_yield_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seeds_planted_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_farm_reports', to=settings.AUTH_USER_MODEL)),
                ('field_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
