# Generated by Django 6.0.3 on 2026-03-31 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0010_farm_location_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seeds_planted_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
