# Generated by Django 5.2.7 on 2026-02-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0010_farm_location_userprofile_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='owner',
            new_name='farmer',
        ),
    ]
