# Generated by Django 5.2.7 on 2026-03-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0011_rename_owner_farm_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
