# Generated by Django 6.0.5 on 2026-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0011_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
