# Generated by Django 5.2.6 on 2026-05-05 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0017_userprofile_must_change_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmAssessmentSheet1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('household_size', models.CharField(choices=[('1-2', '1–2 people'), ('3-5', '3–5 people'), ('6-8', '6–8 people'), ('9+', '9+ people')], max_length=20)),
                ('belongs_to_group', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('farmer_group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('gps_captured', models.BooleanField(default=False)),
                ('land_ownership', models.CharField(choices=[('own', 'Own'), ('family', 'Family'), ('rented', 'Rented'), ('community', 'Community')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet1_assessments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sheet1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmAssessmentSheet2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_size_category', models.CharField(choices=[('small', 'Small (less than 2 acres)'), ('medium', 'Medium (2–5 acres)'), ('large', 'Large (more than 5 acres)')], max_length=20)),
                ('cocoa_tree_age', models.CharField(choices=[('young', 'Young trees'), ('mature', 'Mature trees'), ('old', 'Old trees')], max_length=20)),
                ('has_shade_trees', models.CharField(choices=[('none', 'None'), ('few', 'Few trees'), ('many', 'Many trees')], max_length=20)),
                ('shade_tree_types', models.CharField(blank=True, choices=[('fruit', 'Fruit trees'), ('timber', 'Timber trees'), ('mixed', 'Mixed')], max_length=100)),
                ('uses_fertilizer', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('fertilizer_application', models.CharField(blank=True, choices=[('none', 'None'), ('hand', 'By hand'), ('machine', 'With machine')], max_length=20)),
                ('burns_farm_waste', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often')], max_length=20)),
                ('practices_agroforestry', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('received_training', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('plants_trees', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet2_assessments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sheet2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmAssessmentSheet3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_harvest_bags', models.CharField(choices=[('0-5', '0–5 bags'), ('6-10', '6–10 bags'), ('11-20', '11–20 bags'), ('21+', '21+ bags')], max_length=20)),
                ('harvest_compared_to_last_year', models.CharField(choices=[('more', 'More'), ('same', 'Same'), ('less', 'Less')], max_length=20)),
                ('photo_of_farmer', models.ImageField(blank=True, null=True, upload_to='farm_assessments/farmer_photos/')),
                ('photo_of_farm', models.ImageField(blank=True, null=True, upload_to='farm_assessments/farm_photos/')),
                ('photo_of_cocoa_trees', models.ImageField(blank=True, null=True, upload_to='farm_assessments/cocoa_photos/')),
                ('photo_of_shade_trees', models.ImageField(blank=True, null=True, upload_to='farm_assessments/shade_photos/')),
                ('voice_note', models.FileField(blank=True, help_text='Optional voice note from farmer', null=True, upload_to='farm_assessments/voice_notes/')),
                ('photos_complete', models.BooleanField(default=False)),
                ('data_validated', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet3_assessments', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sheet3', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
