# Generated by Django 5.2.6 on 2026-05-05 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0018_farmassessmentsheet1_farmassessmentsheet2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmassessmentsheet2',
            name='fertilizer_bag_range',
            field=models.CharField(choices=[('none', 'None'), ('1-2', '1-2 bags'), ('3-5', '3-5 bags'), ('5+', 'More than 5 bags')], default='none', max_length=20),
        ),
    ]
