# Generated by Django 5.2.6 on 2026-05-06 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0019_farmassessmentsheet2_fertilizer_bag_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorDatasetImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=255)),
                ('source_file', models.FileField(upload_to='investor_uploads/%Y/%m/%d/')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'XLSX')], max_length=10)),
                ('schema', models.JSONField(blank=True, default=list)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('imported', 'Imported'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestorDatasetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('fingerprint', models.TextField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='Farmers.investordatasetimport')),
            ],
            options={
                'ordering': ['row_number'],
                'indexes': [models.Index(fields=['dataset', 'fingerprint'], name='Farmers_inv_dataset_d0b92b_idx'), models.Index(fields=['dataset', 'row_number'], name='Farmers_inv_dataset_e0c89d_idx')],
            },
        ),
    ]
