# Generated by Django 5.2.6 on 2026-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0022_datasetauditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='datasetauditlog',
            new_name='Farmers_dat_actor_i_929b0a_idx',
            old_name='Farmers_dat_actor_i_32cc17_idx',
        ),
        migrations.RenameIndex(
            model_name='datasetauditlog',
            new_name='Farmers_dat_action_339f8f_idx',
            old_name='Farmers_dat_action__00d260_idx',
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='confirmed_domain',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture/Farm Data'), ('finance', 'Financial/Business Data'), ('hr', 'Human Resources Data'), ('inventory', 'Inventory/Logistics Data'), ('carbon_esg', 'Carbon/ESG Data'), ('general', 'General Analytics Data'), ('custom', 'Custom/Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='inferred_domain',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture/Farm Data'), ('finance', 'Financial/Business Data'), ('hr', 'Human Resources Data'), ('inventory', 'Inventory/Logistics Data'), ('carbon_esg', 'Carbon/ESG Data'), ('general', 'General Analytics Data'), ('custom', 'Custom/Unknown')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='inferred_domain_confidence',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='inferred_domain_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('analyst', 'Analyst'), ('field_agent', 'Field Agent'), ('admin', 'Admin')], default='farmer', max_length=20),
        ),
    ]
