# Generated by Django 5.2.6 on 2026-05-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0023_rename_farmers_dat_actor_i_32cc17_idx_farmers_dat_actor_i_929b0a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investordatasetimport',
            name='column_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='prep_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='prep_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='investordatasetimport',
            name='row_operations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
