# Generated by Django 5.2.6 on 2026-05-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0025_expand_dataset_formats_and_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmassessmentsheet2',
            name='year_planted',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year cocoa was first planted on this farm.', null=True),
        ),
    ]
