# Generated by Django 5.2.6 on 2026-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0026_add_year_planted_to_sheet2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmassessmentsheet2',
            name='cocoa_tree_age',
        ),
        migrations.RemoveField(
            model_name='farmassessmentsheet3',
            name='harvest_compared_to_last_year',
        ),
        migrations.RemoveField(
            model_name='farmassessmentsheet3',
            name='last_harvest_bags',
        ),
        migrations.AddField(
            model_name='farmassessmentsheet3',
            name='harvest_history',
            field=models.JSONField(blank=True, default=dict, help_text='Per-year harvest bag ranges collected at intake (up to 3 years).'),
        ),
    ]
