# Generated by Django 5.2.6 on 2026-05-11 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0027_remove_cocoa_tree_age_add_harvest_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('all_farmers', 'All Farmers'), ('all_field_agents', 'All Field Agents'), ('all', 'Everyone (Farmers & Field Agents)'), ('agent_farmers', "Agent's Farmers")], default='all', max_length=20),
        ),
    ]
