# Generated by Django 5.2.6 on 2026-05-17 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmers', '0030_contactsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmactivity',
            name='additional_trees_added',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='admin_approval_status',
            field=models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected by Admin')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='admin_review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='admin_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='admin_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewed_farm_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='agent_verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='habit_changed_from',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='habit_changed_to',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='tool_changed_from',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='tool_changed_to',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Field Agent Verification'), ('verified', 'Verified by Field Agent'), ('rejected', 'Rejected by Field Agent')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmactivity',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_farm_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='farmactivity',
            name='activity_type',
            field=models.CharField(choices=[('additional_trees', 'Additional Trees Added'), ('tool_change', 'Change of Tool'), ('habit_change', 'Change of Habit'), ('planting', 'Planting'), ('pruning', 'Pruning'), ('spraying', 'Spraying'), ('harvesting', 'Harvesting')], max_length=20),
        ),
    ]
